#!/usr/bin/env python3
"""Rear Drive Unit resolver calibration over UDS (DIR, ODIN node "DI").

Re-runs the two on-motor resolver learns after an inverter swap when the OLD
unit's stored calibration is unavailable (e.g. an EV conversion where the donor
inverter arrived without its matched-motor data). Firmware-derived from a
2020 / gen-26 DIR image.

  1. OFFSET_LEARNING   (RoutineControl 0x0406) -- resolver->rotor electrical
     angle offset. THIS is the usual "runs but poorly" fix: a swapped-in
     inverter carries the PREVIOUS motor's offset, so field-oriented control
     commutates off-axis (low torque, high current, rough). Regenerates
     SPEED_SENSOR_ANGLE_OFFSET (DID 0x0306). Needs SecurityAccess level 5.
  2. RESOLVER_LEARNING (RoutineControl 0x0407) -- the 92-point angle-error
     table over one revolution (analog resolver error). Writes
     RESOLVER_CALIBRATION_DATA (DID 0x030B). No security required.

Order matters: OFFSET first (coarse alignment), then RESOLVER (fine per-angle
table, measured against a correct offset). Both routines persist to EEPROM
themselves -- no separate DID write needed.

This tool drives ONLY the UDS side. The CAN preconditions must already be met by
vehicle_sim.py running alongside, and by the operator spinning the motor:

  python scripts/vehicle_sim.py --channel <A> --party-channel <B> \
         --traction-mode dyno

Firmware gates (DIR precondition checks, RE-confirmed):
  * DIR_readTractionControlMode == 5 (TC_DYNO_MODE)   <- vehicle_sim --traction-mode dyno
      (CAN 0x293 UI_chassisControl, UI_tractionControlMode = 5)
  * immobilizer DISARMED (0x118 immo state == 3)      <- vehicle_sim immo responder
  * motor SPINNING, valid gear, above the speed gate  <- physical accelerator
      (the 2020 RWD pedal is hardwired, not CAN, so YOU spin it)
  * TesterPresent held (else OFFSET -> FAIL_NO_TESTER_PRESENT)  <- this tool

Usage:
  python scripts/di/resolver_cal.py --channel can0             # full: offset then table
  python scripts/di/resolver_cal.py --offset-only
  python scripts/di/resolver_cal.py --table-only
  python scripts/di/resolver_cal.py --reset --table-only       # zero the cal table first
  python scripts/di/resolver_cal.py --yes --spin-dwell 6       # non-interactive (fixed dwells)
"""
from __future__ import annotations

import argparse
import struct
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

import config as _cfg  # noqa: E402
from uds_local.client import UdsError, UdsSession  # noqa: E402
from uds_local.node_config import load_node_config  # noqa: E402

# --- RoutineControl identifiers + sub-functions (ISO 14229) ---------------------------
RID_OFFSET_LEARN = 0x0406   # OFFSET_LEARNING   (secFlag=1 in the DIR descriptor)
RID_RESOLVER_LEARN = 0x0407  # RESOLVER_LEARNING (secFlag=0)
RC_START = 0x01
RC_STOP = 0x02
RC_RESULTS = 0x03

# --- DataIdentifiers (DIR / DI.odj) ---------------------------------------------------
DID_RESOLVER_CAL = 0x030B          # VERSION u16 @0, ANGLE_OFFSET @2, ANGLE_ERROR_TABLE 184B @4
DID_SPEED_SENSOR_ANGLE_OFFSET = 0x0306   # regenerated by OFFSET_LEARNING
DID_MOTOR_FLUX_REFERENCE = 0x0309        # NOT learnable (per-motor constant; here for reference)

# DIR security level for these routines / the 0x30B write (matches opc_via_pmr dir_oilpump_status).
_SEC_LEVEL = 0x05

# Result enums, straight from DI.odj (node DIR).
OFFSET_RESULT = {
    0: "SUCCESS", 1: "FAIL_BRAKES", 2: "FAIL_INVALID_GEAR", 3: "FAIL_NEG_SPEED",
    4: "FAIL_OVER_SPEED", 5: "FAIL_CURRENT", 6: "FAIL_TEMPERATURE", 7: "FAIL_TIMEOUT",
    8: "FAIL_NO_TESTER_PRESENT", 9: "FAIL_DI_FAULT", 10: "FAIL_UDS_ABORT",
    11: "FAIL_UNABLE_TO_SHIFT_TO_N", 12: "FAIL_VERIFICATION_VOLTAGE",
    13: "FAIL_VERIFICATION_CURRENT", 14: "FAIL_EEPROM_WRITE",
}
RESOLVER_RESULT = {
    0: "LEARN_SUCCESS", 1: "TEST_FAILED", 2: "OFF_LIMITS", 3: "START_SPEED",
    4: "SPEED_RANGE", 5: "TORQUE", 6: "BRAKE", 7: "FAULT",
}

_OFFSET_SCALE = 2.0 ** -28   # FINAL_OFFSET / FINAL_VD / FINAL_VQ raw -> value
_RMS_SCALE = 1.0 / 512.0     # RMSERROR raw -> value


# =====================================================================================
# result parsing (all multi-byte fields are big-endian on the wire -- the DIR handler
# byte-swaps each word before returning it)
# =====================================================================================
def parse_offset_result(data: bytes) -> dict:
    """OFFSET_LEARNING results = 17 bytes:
    INITIAL_OFFSET/FINAL_OFFSET/FINAL_VD/FINAL_VQ (int32 BE x2^-28) + LEARN_RESULT nibble."""
    if len(data) < 17:
        return {"error": f"short result ({len(data)} < 17 bytes): {data.hex()}"}
    initial, final, vd, vq = struct.unpack_from(">iiii", data, 0)
    code = data[16] & 0x0F
    return {
        "initial_offset": initial * _OFFSET_SCALE,
        "final_offset": final * _OFFSET_SCALE,
        "final_vd": vd * _OFFSET_SCALE,
        "final_vq": vq * _OFFSET_SCALE,
        "result_code": code,
        "result": OFFSET_RESULT.get(code, f"UNKNOWN({code})"),
    }


def parse_resolver_result(data: bytes) -> dict:
    """RESOLVER_LEARNING results = 187 bytes: ERRORTABLE (92 x int16 BE @0..183) +
    RMSERROR (int16 BE @184, x1/512) + LEARN_RESULT/WRITE_FAILED/RUNNING @186."""
    if len(data) < 187:
        return {"error": f"short result ({len(data)} < 187 bytes): {data.hex()}"}
    table = list(struct.unpack_from(">92h", data, 0))
    rms = struct.unpack_from(">h", data, 184)[0] * _RMS_SCALE
    flags = data[186]
    code = flags & 0x07
    return {
        "table": table,
        "rms_error": rms,
        "running": bool((flags >> 4) & 1),
        "write_failed": bool((flags >> 3) & 1),
        "result_code": code,
        "result": RESOLVER_RESULT.get(code, f"UNKNOWN({code})"),
    }


# =====================================================================================
# helpers
# =====================================================================================
def _confirm(prompt: str, auto: bool) -> bool:
    """Interactive y/N gate; auto-yes when --yes."""
    if auto:
        print(f"  [auto] {prompt} -> yes")
        return True
    try:
        return input(f"  {prompt} [y/N] ").strip().lower() in ("y", "yes")
    except EOFError:
        return False


def _dwell(prompt: str, seconds: float, auto: bool) -> None:
    """Either wait for Enter (interactive) or sleep a fixed time (--yes)."""
    if auto:
        print(f"  [auto] {prompt} -- holding {seconds:.1f}s")
        time.sleep(seconds)
    else:
        try:
            input(f"  {prompt} -- press Enter when done ")
        except EOFError:
            time.sleep(seconds)


_START_HINTS = {
    0x10: "generalReject -- precondition not met (check: dyno mode on 0x293, motor spinning "
          "in a valid gear above the speed gate, immobilizer DISARMED)",
    0x22: "conditionsNotCorrect",
    0x33: "securityAccessDenied -- security level 5 not unlocked (0x0406 needs it)",
    0x31: "requestOutOfRange -- routine not supported on this node/firmware",
}


def _routine(sess: UdsSession, rid: int, subtype: int, label: str) -> bytes | None:
    """Issue one RoutineControl sub-function; return payload, or None on NRC (printed)."""
    try:
        resp = sess.routine_control(rid, subtype=subtype)
        print(f"  0x{rid:04X} sub{subtype:02X} {label:<9} -> {resp.hex() or '<empty>'}")
        return resp
    except UdsError as e:
        nrc = getattr(e, "nrc", None) or 0
        hint = _START_HINTS.get(nrc, e.nrc_name)
        print(f"  0x{rid:04X} sub{subtype:02X} {label:<9} -> NRC 0x{nrc:02X} ({hint})")
        return None


# =====================================================================================
# DID snapshot / reset
# =====================================================================================
def _read_did(sess: UdsSession, did: int) -> bytes | None:
    try:
        return sess.read_did(did)
    except UdsError as e:
        print(f"  read 0x{did:04X} -> NRC 0x{getattr(e, 'nrc', 0):02X} ({e.nrc_name})")
        return None


def snapshot(sess: UdsSession, tag: str) -> None:
    print(f"[snapshot: {tag}]")
    off = _read_did(sess, DID_SPEED_SENSOR_ANGLE_OFFSET)
    if off is not None:
        print(f"  SPEED_SENSOR_ANGLE_OFFSET (0x0306) = {off.hex()}")
    flux = _read_did(sess, DID_MOTOR_FLUX_REFERENCE)
    if flux is not None:
        print(f"  MOTOR_FLUX_REFERENCE      (0x0309) = {flux.hex()}  (not learnable)")
    cal = _read_did(sess, DID_RESOLVER_CAL)
    if cal is not None and len(cal) >= 4:
        version = struct.unpack_from(">H", cal, 0)[0]
        table = cal[4:]
        nonzero = sum(1 for b in table if b)
        print(f"  RESOLVER_CALIBRATION_DATA (0x030B) = version {version}, "
              f"{len(table)}B table, {nonzero} non-zero bytes")
    elif cal is not None:
        print(f"  RESOLVER_CALIBRATION_DATA (0x030B) = {cal.hex()}")


def reset_cal(sess: UdsSession, auto: bool) -> None:
    """Mirror ODIN's PROC_DI_X_RESOLVER-CALIBRATION-DATA: zero VERSION + ANGLE_ERROR_TABLE,
    keep ANGLE_OFFSET, write back (needs security lvl5). Optional -- the learn overwrites it."""
    cal = _read_did(sess, DID_RESOLVER_CAL)
    if cal is None or len(cal) < 4:
        print("  reset: could not read current 0x030B; skipping")
        return
    if not _confirm("zero the resolver calibration table (0x030B) before learning?", auto):
        print("  reset: skipped")
        return
    buf = bytearray(cal)
    buf[0:2] = b"\x00\x00"          # VERSION = 0
    buf[4:] = b"\x00" * (len(buf) - 4)  # ANGLE_ERROR_TABLE = 0 (ANGLE_OFFSET @2:4 kept)
    try:
        sess.write_did(DID_RESOLVER_CAL, bytes(buf))
        print("  reset: 0x030B table zeroed")
    except UdsError as e:
        print(f"  reset: write 0x030B -> NRC 0x{getattr(e, 'nrc', 0):02X} ({e.nrc_name})")


# =====================================================================================
# the two learns
# =====================================================================================
def run_offset_learn(sess: UdsSession, args) -> int | None:
    """OFFSET_LEARNING (0x0406): START -> spin steadily -> STOP (finalize) -> RESULTS."""
    print("\n=== OFFSET_LEARNING (0x0406) -- resolver->rotor angle offset ===")
    if not _confirm("motor spinning in a driven gear, above the speed gate, dyno mode on?", args.yes):
        print("  offset: aborted by operator")
        return None
    if _routine(sess, RID_OFFSET_LEARN, RC_START, "start") is None:
        return None
    _dwell("hold the motor spinning steadily", args.spin_dwell, args.yes)
    _routine(sess, RID_OFFSET_LEARN, RC_STOP, "stop")
    time.sleep(0.3)
    resp = _routine(sess, RID_OFFSET_LEARN, RC_RESULTS, "results")
    if resp is None:
        return None
    r = parse_offset_result(resp)
    if "error" in r:
        print(f"  {r['error']}")
        return None
    print(f"  INITIAL_OFFSET = {r['initial_offset']:+.6f}   FINAL_OFFSET = {r['final_offset']:+.6f}")
    print(f"  FINAL_Vd = {r['final_vd']:+.6f}   FINAL_Vq = {r['final_vq']:+.6f}")
    _print_verdict("OFFSET_LEARNING", r["result_code"], r["result"], ok_code=0)
    return r["result_code"]


def run_resolver_learn(sess: UdsSession, args) -> int | None:
    """RESOLVER_LEARNING (0x0407): START -> spin up past the gate then COAST -> poll RESULTS."""
    print("\n=== RESOLVER_LEARNING (0x0407) -- 92-point angle-error table ===")
    if not _confirm("motor ready to spin up then coast, dyno mode on?", args.yes):
        print("  resolver: aborted by operator")
        return None
    if _routine(sess, RID_RESOLVER_LEARN, RC_START, "start") is None:
        return None
    if args.yes:
        print(f"  [auto] spin up past the speed gate then release -- capturing for {args.coast_timeout:.0f}s")
    else:
        input("  spin the motor up past the gate, then RELEASE and let it coast -- press Enter ")

    deadline = time.monotonic() + args.coast_timeout
    last = None
    r = None
    while time.monotonic() < deadline:
        resp = _routine(sess, RID_RESOLVER_LEARN, RC_RESULTS, "results")
        if resp is None:
            return None
        r = parse_resolver_result(resp)
        if "error" in r:
            print(f"  {r['error']}")
            return None
        state = (r["running"], r["result_code"])
        if state != last:
            print(f"  running={r['running']}  result={r['result']}  rms={r['rms_error']:.4f}")
            last = state
        if not r["running"]:
            break
        time.sleep(0.5)
    else:
        print("  resolver: timed out waiting for RUNNING to clear; reporting last result")

    if r is None:
        print("  resolver: no results read (coast-timeout too short?)")
        return None
    nz = sum(1 for v in r["table"] if v)
    print(f"  RMSERROR = {r['rms_error']:.4f}   error table: {nz}/92 non-zero"
          + ("   WRITE_FAILED" if r["write_failed"] else ""))
    if args.dump_table:
        print("  table (92 x int16): " + " ".join(str(v) for v in r["table"]))
    _print_verdict("RESOLVER_LEARNING", r["result_code"], r["result"], ok_code=0)
    return r["result_code"]


def _print_verdict(name: str, code: int, label: str, ok_code: int) -> None:
    mark = "OK" if code == ok_code else "FAIL"
    print(f"  => {name}: {label} ({mark})")


# =====================================================================================
def main() -> int:
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--channel", default=None, help="CAN channel the DIR is on (e.g. can0)")
    p.add_argument("--interface", default=None, help="python-can interface (default socketcan)")
    p.add_argument("--offset-only", action="store_true", help="run only OFFSET_LEARNING (0x0406)")
    p.add_argument("--table-only", action="store_true", help="run only RESOLVER_LEARNING (0x0407)")
    p.add_argument("--reset", action="store_true",
                   help="zero RESOLVER_CALIBRATION_DATA (0x030B) before learning (ODIN reset step)")
    p.add_argument("--no-security", action="store_true",
                   help="skip SecurityAccess (0x0407 works without it; 0x0406 will NRC 0x33)")
    p.add_argument("--spin-dwell", type=float, default=5.0,
                   help="(--yes) seconds to hold the motor spinning during OFFSET_LEARNING")
    p.add_argument("--coast-timeout", type=float, default=60.0,
                   help="max seconds to poll RESOLVER_LEARNING results (spin-up + coast-down)")
    p.add_argument("--dump-table", action="store_true", help="print the 92 int16 error-table values")
    p.add_argument("--yes", "-y", action="store_true",
                   help="non-interactive: auto-confirm and use fixed dwells (motor WILL spin)")
    _cfg.apply_defaults(p)
    args = p.parse_args()

    if args.offset_only and args.table_only:
        p.error("--offset-only and --table-only are mutually exclusive")
    if not args.channel:
        p.error("--channel is required (or set it in .env)")

    print(__doc__.split("\n\n")[0])
    print("PREREQUISITES (must already be running): vehicle_sim.py --traction-mode dyno "
          "(immo DISARM + dyno mode + liveness), and be ready to spin the motor.\n")

    cfg = load_node_config("DIR", _cfg.NODES_JSON, _cfg.ETH_COMPACT, _cfg.ODJ_DIR)
    codes: list[tuple[str, int | None]] = []
    with UdsSession(cfg, args.channel, interface=args.interface) as sess:
        sess.diagnostic_session(0x03)      # extended session
        sess.start_tester_present()        # keep-alive (else OFFSET FAIL_NO_TESTER_PRESENT)
        try:
            if not args.no_security:
                try:
                    sess.security_access(level_idx=0, seed_level=_SEC_LEVEL)
                    print("[dir] security level 5 unlocked")
                except UdsError as e:
                    print(f"[dir] security unlock FAILED: NRC 0x{getattr(e, 'nrc', 0):02X} "
                          f"({e.nrc_name}) -- 0x0406 will NRC 0x33; 0x0407 can still run")

            snapshot(sess, "before")
            if args.reset and not args.offset_only:
                reset_cal(sess, args.yes)

            codes = []
            if not args.table_only:
                codes.append(("OFFSET", run_offset_learn(sess, args)))
            if not args.offset_only:
                codes.append(("RESOLVER", run_resolver_learn(sess, args)))

            snapshot(sess, "after")
        finally:
            sess.stop_tester_present()

    print("\n=== summary ===")
    ok = True
    for name, code in codes:
        verdict = "SUCCESS" if code == 0 else (f"code {code}" if code is not None else "not run/aborted")
        print(f"  {name}: {verdict}")
        ok = ok and code == 0
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
